export const TransactionActionTypes = {
  BUY_STOCK: "BUY_STOCK",
  SELL_STOCK: "SELL_STOCK",
  TOGGLE_TRANSACTION_FORM: "TOGGLE_TRANSACTION_FORM",
  SET_FORM_COORDINATES: "SET_FORM_COORDINATES",
  CANCEL_PENDING_TRANSACTION: "CANCEL_PENDING_TRANSACTION",
  HANDLE_COMPLETED_TRANSACTION: "HANDLE_COMPLETED_TRANSACTION",
  MODIFY_TRANSACTION: "MODIFY_TRANSACTION",
};
