export const WatchlistActionTypes = {
  SET_WATCHLIST: "SET_WATCHLIST",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  SET_NAME: "SET_NAME",
  SET_SELECTED_WATCHLIST: "SET_SELECTED_WATCHLIST",
  CREATE_WATCHLIST: "CREATE_WATCHLIST",
  HANDLE_ITEM_IN_TRANSACTION: "HANDLE_ITEM_IN_TRANSACTION",
  DELETE_WATCHLIST: "DELETE_WATCHLIST",
};
