export const WatchlistActionTypes = {
  SET_WATCHLIST: "SET_WATCHLIST",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  SET_NAME: "SET_NAME",
  SET_SELECTED_WATCHLIST: "SET_SELECTED_WATCHLIST",
};
